//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminClientes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminClientes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AdminClientes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Cliente.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir direccion.
        /// </summary>
        internal static string BtnAddDireccion {
            get {
                return ResourceManager.GetString("BtnAddDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir telefono.
        /// </summary>
        internal static string BtnAddTelefono {
            get {
                return ResourceManager.GetString("BtnAddTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir transporte.
        /// </summary>
        internal static string BtnAddTransporte {
            get {
                return ResourceManager.GetString("BtnAddTransporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar seleccionados.
        /// </summary>
        internal static string BtnEliminar {
            get {
                return ResourceManager.GetString("BtnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo cliente.
        /// </summary>
        internal static string BtnNuevo {
            get {
                return ResourceManager.GetString("BtnNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        internal static string gridClientesActivo {
            get {
                return ResourceManager.GetString("gridClientesActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Precio.
        /// </summary>
        internal static string gridClientesCatListaPrecio {
            get {
                return ResourceManager.GetString("gridClientesCatListaPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria Tributaria.
        /// </summary>
        internal static string gridClientesCatTributaria {
            get {
                return ResourceManager.GetString("gridClientesCatTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuit.
        /// </summary>
        internal static string gridClientesCuit {
            get {
                return ResourceManager.GetString("gridClientesCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string gridClientesFecha {
            get {
                return ResourceManager.GetString("gridClientesFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        internal static string gridClientesID {
            get {
                return ResourceManager.GetString("gridClientesID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mail.
        /// </summary>
        internal static string gridClientesMail {
            get {
                return ResourceManager.GetString("gridClientesMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string gridClientesNombre {
            get {
                return ResourceManager.GetString("gridClientesNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RazonSocial.
        /// </summary>
        internal static string gridClientesRazonSocial {
            get {
                return ResourceManager.GetString("gridClientesRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion Envio.
        /// </summary>
        internal static string lblDireccionEnvio {
            get {
                return ResourceManager.GetString("lblDireccionEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIRECCIONES.
        /// </summary>
        internal static string lblDirecciones {
            get {
                return ResourceManager.GetString("lblDirecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion Real.
        /// </summary>
        internal static string lblDireccionReal {
            get {
                return ResourceManager.GetString("lblDireccionReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista Precio.
        /// </summary>
        internal static string lblNuevoClienteCatListaPrecio {
            get {
                return ResourceManager.GetString("lblNuevoClienteCatListaPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria Tributaria.
        /// </summary>
        internal static string lblNuevoClienteCatTributaria {
            get {
                return ResourceManager.GetString("lblNuevoClienteCatTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CUIT.
        /// </summary>
        internal static string lblNuevoClienteCuit {
            get {
                return ResourceManager.GetString("lblNuevoClienteCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMAIL.
        /// </summary>
        internal static string lblNuevoClienteEmail {
            get {
                return ResourceManager.GetString("lblNuevoClienteEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string lblNuevoClienteNombre {
            get {
                return ResourceManager.GetString("lblNuevoClienteNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razon Social.
        /// </summary>
        internal static string lblNuevoClienteRazonSocial {
            get {
                return ResourceManager.GetString("lblNuevoClienteRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TELEFONOS.
        /// </summary>
        internal static string lblTelefonos {
            get {
                return ResourceManager.GetString("lblTelefonos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TRANSPORTES.
        /// </summary>
        internal static string lblTransportes {
            get {
                return ResourceManager.GetString("lblTransportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese CUIT.
        /// </summary>
        internal static string phNuevoClienteCuit {
            get {
                return ResourceManager.GetString("phNuevoClienteCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese EMAIL.
        /// </summary>
        internal static string phNuevoClienteEmail {
            get {
                return ResourceManager.GetString("phNuevoClienteEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese nombre.
        /// </summary>
        internal static string phNuevoClienteNombre {
            get {
                return ResourceManager.GetString("phNuevoClienteNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese razon social.
        /// </summary>
        internal static string phNuevoClienteRazonSocial {
            get {
                return ResourceManager.GetString("phNuevoClienteRazonSocial", resourceCulture);
            }
        }
    }
}
