//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminArticulos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminArticulos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AdminArticulos", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Articulo.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar seleccionados.
        /// </summary>
        internal static string BtnEliminar {
            get {
                return ResourceManager.GetString("BtnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo articulo.
        /// </summary>
        internal static string BtnNuevo {
            get {
                return ResourceManager.GetString("BtnNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        internal static string gridArticulosActivo {
            get {
                return ResourceManager.GetString("gridArticulosActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo de Barra.
        /// </summary>
        internal static string gridArticulosCodbarra {
            get {
                return ResourceManager.GetString("gridArticulosCodbarra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        internal static string gridArticulosColor {
            get {
                return ResourceManager.GetString("gridArticulosColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        internal static string gridArticulosID {
            get {
                return ResourceManager.GetString("gridArticulosID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo.
        /// </summary>
        internal static string gridArticulosModelo {
            get {
                return ResourceManager.GetString("gridArticulosModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Mayorista.
        /// </summary>
        internal static string gridArticulosPreciomay {
            get {
                return ResourceManager.GetString("gridArticulosPreciomay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Minorista.
        /// </summary>
        internal static string gridArticulosPreciomin {
            get {
                return ResourceManager.GetString("gridArticulosPreciomin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talle.
        /// </summary>
        internal static string gridArticulosTalle {
            get {
                return ResourceManager.GetString("gridArticulosTalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione color.
        /// </summary>
        internal static string lblNuevoArticuloColor {
            get {
                return ResourceManager.GetString("lblNuevoArticuloColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione modelo.
        /// </summary>
        internal static string lblNuevoArticuloModelo {
            get {
                return ResourceManager.GetString("lblNuevoArticuloModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese precio mayorista.
        /// </summary>
        internal static string lblNuevoArticuloPreciomay {
            get {
                return ResourceManager.GetString("lblNuevoArticuloPreciomay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese precio minorista.
        /// </summary>
        internal static string lblNuevoArticuloPreciomin {
            get {
                return ResourceManager.GetString("lblNuevoArticuloPreciomin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese stock.
        /// </summary>
        internal static string lblNuevoArticuloStock {
            get {
                return ResourceManager.GetString("lblNuevoArticuloStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione talle.
        /// </summary>
        internal static string lblNuevoArticuloTalle {
            get {
                return ResourceManager.GetString("lblNuevoArticuloTalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el precio mayorista.
        /// </summary>
        internal static string phNuevoArticuloPreciomay {
            get {
                return ResourceManager.GetString("phNuevoArticuloPreciomay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el precio minorista.
        /// </summary>
        internal static string phNuevoArticuloPreciomin {
            get {
                return ResourceManager.GetString("phNuevoArticuloPreciomin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese cantidad de stock.
        /// </summary>
        internal static string phNuevoArticuloStock {
            get {
                return ResourceManager.GetString("phNuevoArticuloStock", resourceCulture);
            }
        }
    }
}
