//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LoginResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesion.
        /// </summary>
        internal static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alguno de los campos no es correcto.
        /// </summary>
        internal static string CamposIncorrectos {
            get {
                return ResourceManager.GetString("CamposIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese usuario y contraseña.
        /// </summary>
        internal static string CamposVacios {
            get {
                return ResourceManager.GetString("CamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese usuario y contraseña.
        /// </summary>
        internal static string Subtitulo {
            get {
                return ResourceManager.GetString("Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesion.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la empresa.
        /// </summary>
        internal static string TxtEmpresaPH {
            get {
                return ResourceManager.GetString("TxtEmpresaPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la contraseña.
        /// </summary>
        internal static string TxtPassPH {
            get {
                return ResourceManager.GetString("TxtPassPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no puede estar vacía.
        /// </summary>
        internal static string TxtPassValidation {
            get {
                return ResourceManager.GetString("TxtPassValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el usuario.
        /// </summary>
        internal static string TxtUserPH {
            get {
                return ResourceManager.GetString("TxtUserPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no puede estar vacío.
        /// </summary>
        internal static string TxtUserValidation {
            get {
                return ResourceManager.GetString("TxtUserValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el usuario.
        /// </summary>
        internal static string TxtUsuario {
            get {
                return ResourceManager.GetString("TxtUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
