//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MenuResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADMINISTRAR.
        /// </summary>
        internal static string menuAdministrar {
            get {
                return ResourceManager.GetString("menuAdministrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a STOCK.
        /// </summary>
        internal static string menuStock {
            get {
                return ResourceManager.GetString("menuStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Articulos.
        /// </summary>
        internal static string submenuAdminArticulos {
            get {
                return ResourceManager.GetString("submenuAdminArticulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Bancos.
        /// </summary>
        internal static string submenuAdminBancos {
            get {
                return ResourceManager.GetString("submenuAdminBancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Categorías Precios.
        /// </summary>
        internal static string submenuAdminCategoriasPrecios {
            get {
                return ResourceManager.GetString("submenuAdminCategoriasPrecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Clientes.
        /// </summary>
        internal static string submenuAdminClientes {
            get {
                return ResourceManager.GetString("submenuAdminClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Colores.
        /// </summary>
        internal static string submenuAdminColores {
            get {
                return ResourceManager.GetString("submenuAdminColores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin Funcionalidades x Rol.
        /// </summary>
        internal static string submenuAdminFuncionalidades {
            get {
                return ResourceManager.GetString("submenuAdminFuncionalidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Localidades.
        /// </summary>
        internal static string submenuAdminLocalidades {
            get {
                return ResourceManager.GetString("submenuAdminLocalidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Modelos.
        /// </summary>
        internal static string submenuAdminModelos {
            get {
                return ResourceManager.GetString("submenuAdminModelos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Paises.
        /// </summary>
        internal static string submenuAdminPaises {
            get {
                return ResourceManager.GetString("submenuAdminPaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Proveedores.
        /// </summary>
        internal static string submenuAdminProveedores {
            get {
                return ResourceManager.GetString("submenuAdminProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Provincias.
        /// </summary>
        internal static string submenuAdminProvincias {
            get {
                return ResourceManager.GetString("submenuAdminProvincias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Roles.
        /// </summary>
        internal static string submenuAdminRoles {
            get {
                return ResourceManager.GetString("submenuAdminRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver stock.
        /// </summary>
        internal static string submenuAdminStock {
            get {
                return ResourceManager.GetString("submenuAdminStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Sucursal.
        /// </summary>
        internal static string submenuAdminSucursales {
            get {
                return ResourceManager.GetString("submenuAdminSucursales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sucursal por usuario.
        /// </summary>
        internal static string submenuAdminSucxUser {
            get {
                return ResourceManager.GetString("submenuAdminSucxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Talles.
        /// </summary>
        internal static string submenuAdminTalles {
            get {
                return ResourceManager.GetString("submenuAdminTalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Telas.
        /// </summary>
        internal static string submenuAdminTelas {
            get {
                return ResourceManager.GetString("submenuAdminTelas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Temporadas.
        /// </summary>
        internal static string submenuAdminTemporadas {
            get {
                return ResourceManager.GetString("submenuAdminTemporadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Tipos de Gastos.
        /// </summary>
        internal static string submenuAdminTiposGastos {
            get {
                return ResourceManager.GetString("submenuAdminTiposGastos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Tipos Productos.
        /// </summary>
        internal static string submenuAdminTiposProductos {
            get {
                return ResourceManager.GetString("submenuAdminTiposProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Transportes.
        /// </summary>
        internal static string submenuAdminTransportes {
            get {
                return ResourceManager.GetString("submenuAdminTransportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Usuarios.
        /// </summary>
        internal static string submenuAdminUsers {
            get {
                return ResourceManager.GetString("submenuAdminUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transferir Stock.
        /// </summary>
        internal static string transferenciaStock {
            get {
                return ResourceManager.GetString("transferenciaStock", resourceCulture);
            }
        }
    }
}
